version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=rodolfo
      - POSTGRES_PASSWORD=
  web:
    build: .
    command: ./script/start
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/market_place_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes_from:
      - box
  box:
    image: busybox
    volumes:
      - /box
